name: Build and Deploy Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configure Docker
      run: |
       docker login -u ubteb -p 123456789


    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        dockerfile: Dockerfile
        push: true
        tags: ubteb/cloudcomputing
